steps:
# Step 1: Docker Build
# - Create a docker image with the tag of commit ID and latest.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_IMAGE_NAME}:$SHORT_SHA', '-t', '${_IMAGE_NAME}:latest', '.']

# Step 2: Docker Push
# - Push image to GCP Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', '${_IMAGE_NAME}']

# Step 3: Kubectl Apply
# - Apply the kubernetes configuration files to the cluster

- name: "gcr.io/cloud-builders/kubectl"
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_LOCATION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  args:
    - apply
    - -f
    - ./kubernetes/service.yaml
    - -f
    - ./kubernetes/pvc.yaml
    - -f
    - ./kubernetes/deployment.yaml

substitutions:
  _IMAGE_NAME: 'us-docker.pkg.dev/${PROJECT_ID}/k8s-assignment/app1'
  _CLUSTER_LOCATION: 'us-central1-c'
  _CLUSTER_NAME: 'k8s-assignment-cluster-1'

options:
  logging: CLOUD_LOGGING_ONLY
